### ISSUE TITLE
MQTT Service : copy function doesn't work

### ISSUE THREAD

**Issue by PhilippeMA** [GladysAssistant/Gladys#756]
**Describe the bug**
Copy function doesn't work

**To Reproduce**

1. Go to 'Edit features'
2. Click on 'Copy MQTT Topic' of any feature
3. Button text disappear and nothing copied

**Your Gladys installation (please complete the following information):**

- Raspberry Pi installation (if yes, which Raspberry Pi ?) Raspberry Pi 3
- Manual installation: [MacOS/Windows/Linux?] Gladys prod

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : Raspbian
- Browser [e.g. chrome, safari] : Firefox
- Version [e.g. 22] : 75
![Peek 27-04-2020 23-20](https://user-images.githubusercontent.com/25247304/80422166-f7841580-88dd-11ea-93a8-682f301bf49d.gif)

**Comment by atrovato** [comment]
Fixed with french translation PR, according to i18n validator.

**Comment by atrovato** [comment]
@PhilippeMA is it fixed now with french translation integration?

**Comment by PhilippeMA** [comment]
Hello @atrovato, i now have a message but copy function still doesn't work.

No log in Gladys and i don't know where i can see logs for this problem in Firefox. Tell me what I can do to give you more information.

![MQTT_copy_bug](https://user-images.githubusercontent.com/25247304/81472218-d7febe00-91f6-11ea-910a-d1032e3dae25.gif)

**Comment by atrovato** [comment]
I you want to see logs, you can open console pressing F12 key.
I just test it with Firefox v68, v75 and upper, on Raspbian and Windows, I can't reproduce it.

Can you provide console logs please?

**Comment by PhilippeMA** [comment]
I have no log (cf. gif below).

One observation, it **works with** the same browser as you when I connect via **gladys plus**. But when I'm local, it doesn't work.
![MQTT_copy_bug_nolog](https://user-images.githubusercontent.com/25247304/81477152-7bab9680-9216-11ea-87c7-d1c2fd5e7759.gif)

**Comment by atrovato** [comment]
That's totally weird.... did you hard refresh the browser on local url?

**Comment by PhilippeMA** [comment]
I tried hard refresh but same bug. 

I tried on another computer and this time, i get a message in console : `navigator.clipboard is undefined`

**Comment by Pierre-Gilles** [comment]
I know what's happening, `navigator.clipboard` is only available on localhost and https website

I guess we'll just disable the feature :)

**Comment by Pierre-Gilles** [comment]
And let the user copy paste by himself

**Comment by atrovato** [comment]
I tried with `document.execCommand('copy');` javascript command, but it need to have a displayed input field. There is some tips to hide it, but I'm not really fan.

See https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f

**Comment by Pierre-Gilles** [comment]
I'm not even sure it'll work. Let's just replace the feature with a "select" option, and the user will do the copy/paste by himself?

**Comment by Pierre-Gilles** [comment]
It was removed, closing this.
